# Generated by Django 6.0.2 on 2026-02-17 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='e.g., Home, Work, Mosque', max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Location',
                'verbose_name_plural': 'User Locations',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('calculation_method', models.CharField(choices=[('mw', 'Muslim World League'), ('egypt', 'Egyptian General Authority'), ('karachi', 'University of Karachi'), ('kuwait', 'Kuwait'), ('qatar', 'Qatar'), ('singapore', 'Singapore'), ('turkey', 'Turkish Diyanet'), ('tehran', 'Institute of Geophysics - Tehran'), ('isna', 'Islamic Society of North America')], default='mw', max_length=20)),
                ('juristic_method', models.CharField(choices=[('shafii', "Shafi'i"), ('hanafi', 'Hanafi')], default='shafii', max_length=10)),
                ('high_latitude_adjustment', models.CharField(choices=[('none', 'None'), ('middle_of_night', 'Middle of Night'), ('seventy_one_minute', '71.7 Minutes'), ('seventy_five_minute', '75 Minutes'), ('angle_based', 'Angle-Based')], default='none', max_length=20)),
                ('fajr_notification', models.BooleanField(default=True)),
                ('dhuhr_notification', models.BooleanField(default=True)),
                ('asr_notification', models.BooleanField(default=True)),
                ('maghrib_notification', models.BooleanField(default=True)),
                ('isha_notification', models.BooleanField(default=True)),
                ('notification_minutes_before', models.IntegerField(default=10, help_text='Minutes before prayer to send notification')),
                ('is_verified', models.BooleanField(default=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('language', models.CharField(default='en', max_length=10)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('sepia', 'Sepia')], default='light', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='locations.city')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
