# Generated by Django 4.2.27 on 2026-03-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_subscription_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionlog',
            name='prayer_name',
            field=models.CharField(blank=True, help_text='Prayer name (fajr, dhuhr, asr, maghrib, isha)', max_length=20),
        ),
    ]
