# Generated by Django 4.2.27 on 2026-02-27 22:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Email address for newsletter', max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the subscription is active')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether email has been verified')),
                ('verification_code', models.CharField(blank=True, help_text='Code for email verification', max_length=50)),
                ('prayer_updates', models.BooleanField(default=True, help_text='Receive prayer time updates')),
                ('important_announcements', models.BooleanField(default=True, help_text='Receive important announcements')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Newsletter Subscription',
                'verbose_name_plural': 'Newsletter Subscriptions',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='draft', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_logs', to='newsletter.newslettersubscription')),
            ],
            options={
                'verbose_name': 'Newsletter Log',
                'verbose_name_plural': 'Newsletter Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
