# Generated by Django 4.2.27 on 2026-03-09 21:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(help_text='Email subject line', max_length=255)),
                ('message', models.TextField(help_text='Email body (plain text)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending…'), ('sent', 'Sent'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('total_sent', models.PositiveIntegerField(default=0, help_text='Number of emails dispatched')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Newsletter Campaign',
                'verbose_name_plural': 'Newsletter Campaigns',
                'ordering': ['-created_at'],
            },
        ),
    ]
