# Generated by Django 4.2.27 on 2026-03-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_supportmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_whatsapp_number', models.CharField(default='+8801738060329', help_text='WhatsApp number that receives mosque registration requests. Include country code, e.g. +8801738060329', max_length=30)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
