# Generated by Django 6.0.2 on 2026-02-19 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='WhatsApp phone number with country code', max_length=20, unique=True)),
                ('country_code', models.CharField(default='+880', help_text='Country code', max_length=5)),
                ('full_phone', models.CharField(blank=True, editable=False, max_length=25)),
                ('notification_types', models.JSONField(default=list, help_text='List of notification types to receive')),
                ('language', models.CharField(choices=[('en', 'English'), ('bn', 'Bangla'), ('ar', 'Arabic'), ('ur', 'Urdu')], default='en', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the WhatsApp number is verified')),
                ('verification_code', models.CharField(blank=True, max_length=10)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notification_minutes_before', models.IntegerField(default=10, help_text='Minutes before prayer to send notification')),
                ('admin_notes', models.TextField(blank=True, help_text='Notes added by admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_subscriptions', to='locations.city')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WhatsApp Notification',
                'verbose_name_plural': 'WhatsApp Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('prayer_name', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('read', 'Read')], default='pending', max_length=20)),
                ('twilio_sid', models.CharField(blank=True, help_text='Twilio message SID', max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('whatsapp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='push_notification.whatsappnotification')),
            ],
            options={
                'verbose_name': 'WhatsApp Notification Log',
                'verbose_name_plural': 'WhatsApp Notification Logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
