# Generated by Django 4.2.27 on 2026-03-03 18:43

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImamUser',
            fields=[
            ],
            options={
                'verbose_name': 'Imam User',
                'verbose_name_plural': 'Imam Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
        ),
    ]
