# Generated by Django 6.0.2 on 2026-02-17 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mosque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_wudu_area', models.BooleanField(default=True)),
                ('has_women_facility', models.BooleanField(default=False)),
                ('has_jumuah', models.BooleanField(default=True)),
                ('has_quran_classes', models.BooleanField(default=False)),
                ('has_ramadan_iftar', models.BooleanField(default=False)),
                ('capacity', models.IntegerField(default=0, help_text='Capacity of the main prayer hall')),
                ('fajr_jamaah', models.TimeField(blank=True, null=True)),
                ('dhuhr_jamaah', models.TimeField(blank=True, null=True)),
                ('asr_jamaah', models.TimeField(blank=True, null=True)),
                ('maghrib_jamaah', models.TimeField(blank=True, null=True)),
                ('isha_jamaah', models.TimeField(blank=True, null=True)),
                ('jumuah_khutbah', models.TimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mosques', to='locations.city')),
            ],
            options={
                'verbose_name': 'Mosque',
                'verbose_name_plural': 'Mosques',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MosqueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mosque_images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='find_mosque.mosque')),
            ],
            options={
                'verbose_name': 'Mosque Image',
                'verbose_name_plural': 'Mosque Images',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
    ]
