# Generated by Django 4.2.27 on 2026-02-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_mosque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosque',
            name='asr_beginning',
            field=models.TimeField(blank=True, help_text='Asr beginning time', null=True),
        ),
        migrations.AddField(
            model_name='mosque',
            name='dhuhr_beginning',
            field=models.TimeField(blank=True, help_text='Dhuhr beginning time', null=True),
        ),
        migrations.AddField(
            model_name='mosque',
            name='fajr_beginning',
            field=models.TimeField(blank=True, help_text='Fajr beginning time', null=True),
        ),
        migrations.AddField(
            model_name='mosque',
            name='isha_beginning',
            field=models.TimeField(blank=True, help_text='Isha beginning time', null=True),
        ),
        migrations.AddField(
            model_name='mosque',
            name='maghrib_sunset',
            field=models.TimeField(blank=True, help_text='Maghrib sunset time', null=True),
        ),
        migrations.AddField(
            model_name='mosque',
            name='sunrise',
            field=models.TimeField(blank=True, help_text='Sunrise time', null=True),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='asr_jamaah',
            field=models.TimeField(blank=True, help_text='Asr jamaah time', null=True),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='dhuhr_jamaah',
            field=models.TimeField(blank=True, help_text='Dhuhr jamaah time', null=True),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='fajr_jamaah',
            field=models.TimeField(blank=True, help_text='Fajr jamaah time', null=True),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='isha_jamaah',
            field=models.TimeField(blank=True, help_text='Isha jamaah time', null=True),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='jumuah_khutbah',
            field=models.TimeField(blank=True, help_text='Jumuah khutbah time', null=True),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='maghrib_jamaah',
            field=models.TimeField(blank=True, help_text='Maghrib jamaah time', null=True),
        ),
    ]
