# Generated by Django 4.2.27 on 2026-02-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_mosque', '0002_mosque_asr_beginning_mosque_dhuhr_beginning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosque',
            name='additional_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mosque',
            name='contact_person',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
