# Generated by Django 4.2.27 on 2026-03-03 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('find_mosque', '0004_favoritemosque'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosque',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_mosques', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MosqueMonthlyPrayerTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('day', models.PositiveIntegerField()),
                ('fajr_adhan', models.TimeField()),
                ('fajr_iqamah', models.TimeField()),
                ('dhuhr_adhan', models.TimeField()),
                ('dhuhr_iqamah', models.TimeField()),
                ('asr_adhan', models.TimeField()),
                ('asr_iqamah', models.TimeField()),
                ('maghrib_adhan', models.TimeField()),
                ('maghrib_iqamah', models.TimeField()),
                ('isha_adhan', models.TimeField()),
                ('isha_iqamah', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_prayer_times', to='find_mosque.mosque')),
            ],
            options={
                'verbose_name': 'Mosque Monthly Prayer Time',
                'verbose_name_plural': 'Mosque Monthly Prayer Times',
                'ordering': ['year', 'month', 'day'],
                'unique_together': {('mosque', 'year', 'month', 'day')},
            },
        ),
    ]
