# Generated by Django 4.2.27 on 2026-03-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_mosque', '0005_mosque_created_by_mosquemonthlyprayertime'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosquemonthlyprayertime',
            name='sunrise',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
