# Generated by Django 4.2.27 on 2026-03-08 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('find_mosque', '0006_mosquemonthlyprayertime_sunrise'),
    ]

    operations = [
        migrations.CreateModel(
            name='MosqueAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mosque_announcements', to=settings.AUTH_USER_MODEL)),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='find_mosque.mosque')),
            ],
            options={
                'verbose_name': 'Mosque Announcement',
                'verbose_name_plural': 'Mosque Announcements',
                'ordering': ['-created_at'],
            },
        ),
    ]
