# Generated by Django 4.2.27 on 2026-03-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_mosque', '0007_mosque_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosquemonthlyprayertime',
            name='jumuah_adhan',
            field=models.TimeField(blank=True, help_text='Jummah Khutbah/Adhan time (Fridays only)', null=True),
        ),
        migrations.AddField(
            model_name='mosquemonthlyprayertime',
            name='jumuah_iqamah',
            field=models.TimeField(blank=True, help_text='Jummah Iqamah time (Fridays only)', null=True),
        ),
    ]
