# Generated by Django 6.0.2 on 2026-02-17 19:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('fajr', models.TimeField()),
                ('sunrise', models.TimeField()),
                ('dhuhr', models.TimeField()),
                ('asr', models.TimeField()),
                ('maghrib', models.TimeField()),
                ('isha', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prayer Time',
                'verbose_name_plural': 'Prayer Times',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PrayerTimeAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prayer_name', models.CharField(choices=[('fajr', 'Fajr'), ('sunrise', 'Sunrise'), ('dhuhr', 'Dhuhr'), ('asr', 'Asr'), ('maghrib', 'Maghrib'), ('isha', 'Isha')], max_length=20)),
                ('adjustment_minutes', models.IntegerField(default=0, help_text='Minutes to add (positive) or subtract (negative) from calculated time')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='locations.city')),
            ],
            options={
                'verbose_name': 'Prayer Time Adjustment',
                'verbose_name_plural': 'Prayer Time Adjustments',
            },
        ),
        migrations.CreateModel(
            name='MonthlyPrayerTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2100)])),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('day', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('fajr', models.TimeField()),
                ('sunrise', models.TimeField()),
                ('dhuhr', models.TimeField()),
                ('asr', models.TimeField()),
                ('maghrib', models.TimeField()),
                ('isha', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_prayer_times', to='locations.city')),
            ],
            options={
                'verbose_name': 'Monthly Prayer Time',
                'verbose_name_plural': 'Monthly Prayer Times',
                'ordering': ['year', 'month', 'day'],
                'unique_together': {('city', 'year', 'month', 'day')},
            },
        ),
    ]
